name: Custom Scan

on:
  push:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest

    container:
      image: justuser0129/sva:latest

    services:
      mysql-container:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Execute Application
      run: |
          mkdir report
          cd report
          curl -m 60 -X GET 'http://localhost:8080/api/v1/sbom/test' | jq '.' > sbom-${{ env.file_name }}-result1.json
          curl -m 60 -X GET 'http://localhost:8080/api/v1/sbom/report?token=${{ env.TRACKER_TOKEN }}&projectId=${{ env.uuid }}&baseUrl=${{ env.BASE_URL }}' | jq '.' > sbom-${{ env.file_name }}-result.json
      env:
        TRACKER_TOKEN: ${{ secrets.TRACKER_TOKEN }}
        BASE_URL: ${{ secrets.TRACKER_URL }}

    - name: Get log
      run : cd report && cat sbom-${{ env.file_name }}-result.json
    
    - name: Upload results
      uses: actions/upload-artifact@v3.1.3
      with:
        name: sbom-${{ env.file_name }}-result
        path: report/sbom-${{ env.file_name }}-result1.json
        if-no-files-found: warn
    

