name: Syft Scan

on:
  push:
    branches:
      - master

jobs:
  syft_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Syft
        run: |
          wget https://github.com/anchore/syft/releases/download/v0.92.0/syft_0.92.0_linux_amd64.tar.gz
          tar -xzvf syft_0.92.0_linux_amd64.tar.gz

      - name: Make Syft executable
        run: |
          ls -l
          mv syft_linux /usr/local/bin/syft
          chmod +x syft_linux
