name: Syft Scan

on:
  push:
    branches:
      - master

jobs:
  syft_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Get Image list
        id: get_containers
        run: |
          images=$(docker ps --format "{{.Image}}")
          echo "$images"
          
      - name: Download Syft
        run: |
          wget https://github.com/anchore/syft/releases/download/v0.92.0/syft_0.92.0_linux_amd64.tar.gz
          tar -xzvf syft_0.92.0_linux_amd64.tar.gz

      - name: Make Syft executable
        run: |
          mv syft /usr/local/bin
          chmod +x /usr/local/bin/syft
          
      - name: Scan and Generate SBOM
        id: scan_and_generate_sbom
        run: |
          image_names_string=$(docker ps --format "{{.Image}}")
          IFS=$'\n' read -ra image_names <<< "$image_names_string"
          for image_name in "${image_names[@]}"; do
            echo "Scanning and Generating SBOM for container: $image_name"
            syft $image_name -o cyclonedx-json > sbom-$image_name.json
          done
          
      - name: Combine SBOMs
        run: cat sbom-*.json > combined-sbom.json

      - name: Upload Combined SBOM
        uses: actions/upload-artifact@v2
        with:
          name: sboms
          path: combined-sbom.json
