name: Custom Scan

on:
  push:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest

    services:
      mysql-container:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
    
    steps:
    - name: Get mysql container name
      run: |
        mysql=$(docker ps --format "{{.Names}}" --filter "ancestor=mysql:latest")
        echo "mysql=$mysql" >> $GITHUB_ENV
    
    - name: Build Application
      run: |
        docker pull justuser0129/sva
        docker run -d --name sva -p 8080:8080 -e SPRING_DATASOURCE_URL=jdbc:mysql://${{ env.mysql }}:3306/sva?createDatabaseIfNotExist=true justuser0129/sva:latest

    - name: sleep 10 seconds
      run: sleep 10

    - name: GET docker ps
      run: docker ps

    - name: GET logs
      run: docker logs sva
    
    - name: Build and Execute Application
      run: |
          mkdir report && cd report
          curl -m 60 -X GET 'http://${{ env.contip }}:8080/api/v1/sbom/test' > sbom--result1.json
    
    - name: Upload results
      uses: actions/upload-artifact@v3.1.3
      with:
        name: sbom--result
        path: report/sbom--result1.json
        if-no-files-found: warn
