name: Syft Scan

on:
  push:
    branches:
      - master

jobs:
  scan:
    strategy:
      matrix:
        service:
          - springcommunity/spring-petclinic-customers-service
          - springcommunity/spring-petclinic-api-gateway
          - springcommunity/spring-petclinic-visits-service
          - springcommunity/spring-petclinic-admin-server
          - springcommunity/spring-petclinic-vets-service
          - springcommunity/spring-petclinic-discovery-server
          - springcommunity/spring-petclinic-config-server
          - spring-petclinic-microservices_prometheus-server
          - openzipkin/zipkin
          - spring-petclinic-microservices_grafana-server
        uuid:
         - 9880c46e-53ba-45b4-8241-90e2d769deb6
         - c89d2d96-a385-4dc4-9c8b-7ee50432165c
         - de9c0cf5-c28a-4b88-bd63-5d12cbffe869
         - 8dc6df9b-e1d5-4520-882b-1ccf263d808f
         - 97ac11f5-4310-4bd9-bb8f-7711c2ab9234
         - 18b3f8d6-c497-413b-94c3-007b9224719a
         - fc4c86a6-1e78-453c-b086-2169857688bd
         - 3c1edbdc-b7d7-4eb1-89ad-ca944218459d
         - 596d6ae7-155a-4748-8e86-4551a838c0d7
         - c367fabe-7864-4bdb-994e-3981270777f1

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract image name suffix
      run: |
        image_name="${{ matrix.service }}"
        image_suffix="${image_name#*/}"
        echo "image_suffix=${image_suffix}" >> $GITHUB_ENV

    - name: Execute docker-compose
      run: docker-compose up -d

    - name: Scan the image and upload dependency results
      uses: anchore/sbom-action@v0.14.3
      with:
        image: ${{ matrix.service }}
        format: cyclonedx-json
        artifact-name: sbom-${{ env.image_suffix }}-cyclonedx.json
        github-token: ${{ secrets.PERSONAL_TOKEN }}
        dependency-snapshot: true

    - name: Build SBOM Vulnerability Analyzer
      run: |
        docker pull justuser0129/sva
        docker build -t justuser0129/sva .
        docker run -d -p 7777:8080 justuser0129/sva

    - name: SBOM Scan and Export Result
      run: |
        mkdir report
        cd report
        curl -X GET 'http://localhost:7777/api/v1/sbom/report?token=${{ secrets.TRACKER_TOKEN }}&projectId=${{ matrix.uuid }}&baseUrl=${{ secrets.TRACKER_URL }}' -H 'accept: application/json;charset=UTF-8' | jq '.' > sbom-${{ env.image_suffix }}-result.json

    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: sbom-${{ env.image_suffix }}-result
        path: report/sbom-${{ env.image_suffix }}-result.json
    

