# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Syft Scan

on:
  push:
    branches:
      - main

jobs:
  syft_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Get container list
        id: get_containers
        run: |
          container_names=$(docker-compose ps --services)
          echo "::set-output name=containers::$container_names"

      - name: Install Syft
        run: |
          wget https://github.com/anchore/syft/releases/download/v0.16.0/syft-linux -O /usr/local/bin/syft
          chmod +x /usr/local/bin/syft

      - name: Scan and Generate SBOM
        id: scan_and_generate_sbom
        run: |
          containers="${{ steps.get_containers.outputs.containers }}"
          for container_name in $containers; do
            echo "Scanning and Generating SBOM for container: $container_name"
            syft list -i docker://$container_name --output-format cyclonedx > sbom-$container_name.json
          done

      - name: Upload SBOMs
        uses: actions/upload-artifact@v2
        with:
          name: sboms
          path: sbom-*.json
