name: Custom Scan

on:
  push:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Execute Application
      run: |
          mkdir report && cd report
          curl -m 60 -X GET ${{ secrets.CONTAINER_URL }}/api/v1/sbom/test > sbom--result1.json
    
    - name: Upload results
      uses: actions/upload-artifact@v3.1.3
      with:
        name: sbom--result
        path: report/sbom--result1.json
        if-no-files-found: warn
