name: Syft Scan

on:
  push:
    branches:
      - master

jobs:
  scan:
    strategy:
      matrix:
        service:
          - springcommunity/spring-petclinic-customers-service
          - springcommunity/spring-petclinic-api-gateway
          - springcommunity/spring-petclinic-visits-service
          - springcommunity/spring-petclinic-admin-server
          - springcommunity/spring-petclinic-vets-service
          - springcommunity/spring-petclinic-discovery-server
          - springcommunity/spring-petclinic-config-server
          - spring-petclinic-microservices_prometheus-server
          - openzipkin/zipkin
          - spring-petclinic-microservices_grafana-server

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract image name suffix
      run: |
        image_name="${{ matrix.service }}"
        image_suffix="${image_name#*/}"
        echo "::set-output name=image_suffix::$image_suffix"

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Docker image
      run: |
        docker pull ${{ matrix.service }}
        docker build -t ${{ matrix.service }} .

    - name: Scan the image and upload dependency results
      uses: anchore/sbom-action@bb716408e75840bbb01e839347cd213767269d4a
      with:
        image: ${{ matrix.service }}
        format: cyclonedx-json
        artifact-name: sbom-${{ steps.extract_image_name.outputs.image_suffix }}-cyclonedx.json
        github-token: ${{ secrets.PERSONAL_TOKEN }}
        dependency-snapshot: true
