name: Custom Scan

on:
  push:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest

    container:
      image: justuser0129/sva:latest
      ports:
        - 8080:8080
    
    services:
      mysql-container:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
    
    steps:
    - name: Get mysql container name
      run: |
        sva=$(docker ps -a --format "{{.Names}}" --filter "ancestor=justuser0129/sva:latest")
        echo "sva=$sva" >> $GITHUB_ENV

    - name: sleep 10 seconds
      run: sleep 10

    - name: GET docker ps
      run: docker ps

    - name: GET logs
      run: docker logs ${{ env.sva }}
    
    - name: Build and Execute Application
      run: |
          mkdir report && cd report
          curl -m 60 -X GET 'http://localhost:8080/api/v1/sbom/test' > sbom--result1.json
    
    - name: Upload results
      uses: actions/upload-artifact@v3.1.3
      with:
        name: sbom--result
        path: report/sbom--result1.json
        if-no-files-found: warn
