name: Custom Scan

on:
  push:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest

    container:
      image: justuser0129/sva:latest
      ports:
        - 8080:8080

    services:
      mysql-container:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Execute Application
      run: |
          mkdir report && cd report
          curl -m 60 -X GET 'http://127.0.0.1:8080/api/v1/sbom/test' > sbom--result1.json
    
    - name: Upload results
      uses: actions/upload-artifact@v3.1.3
      with:
        name: sbom--result
        path: report/sbom--result1.json
        if-no-files-found: warn
